### ISSUE TITLE
Add aux-water heat service

### ISSUE THREAD

**Issue by elden1337** [elden1337/hass-peaqhvac#108]
Use this script as template:

```yaml
alias: Nibe - short water boost
sequence:
  - choose:
      - conditions:
          - condition: numeric_state
            entity_id: >-
              sensor.f730_cu_3x400v_magnus_nibef_f730_cu_3x400v_hot_water_charging_bt6
            below: 40
        sequence:
          - service: switch.turn_on
            target:
              entity_id: switch.f730_cu_3x400v_magnus_nibef_f730_cu_3x400v_temporary_lux
            data: {}
          - wait_template: >-
              {{states.sensor.f730_cu_3x400v_magnus_nibef_f730_cu_3x400v_hot_water_charging_bt6.state|float
              >= 40}}
            continue_on_timeout: true
            timeout: "1200"
          - service: switch.turn_off
            target:
              entity_id: switch.f730_cu_3x400v_magnus_nibef_f730_cu_3x400v_temporary_lux
            data: {}
    default:
      - service: switch.turn_on
        target:
          entity_id: switch.f730_cu_3x400v_magnus_nibef_f730_cu_3x400v_temporary_lux
        data: {}
      - delay:
          hours: 0
          minutes: 20
          seconds: 0
          milliseconds: 0
      - service: switch.turn_off
        target:
          entity_id: switch.f730_cu_3x400v_magnus_nibef_f730_cu_3x400v_temporary_lux
        data: {}
mode: single
icon: mdi:water-boiler
```
